-- SQL 하나 수행 :  CTRL + ENTER
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 실습용 사용자 계정 생성
CREATE USER kh_khd IDENTIFIED BY Myodong312;

--  사용자 계정 권한 부여
GRANT RESOURCE, CONNECT TO kh_khd;

-- 객채 생성(테이블 등) 공간 할당량 지정
ALTER USER kh_khd DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;